import React from 'react';
import {StyleSheet} from 'react-native';
import {scale} from 'react-native-size-matters';

const styles = StyleSheet.create({
  topcontainer: {
    height: scale(115),
    backgroundColor: '#f2f2f2',
    alignItems: 'center',
  },
  topsmaller: {
    height: scale(85),
    backgroundColor: '#f2f2f2',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  searchcontainer: {
    height: scale(70),
    backgroundColor: '#f2f2f2',
    justifyContent: 'center',
    alignItems: 'center',
  },
  datacontainer: {
    height: scale(400),
    backgroundColor: '#f2f2f2',
  },
  item: {
    padding: scale(10),
    marginVertical: scale(5),
    marginHorizontal: scale(15),
    flexDirection: 'row',
    alignItems: 'center',
  },
  title: {
    fontSize: scale(20),
  },
  toptext: {
    marginTop: scale(10),
    fontSize: scale(50),
    color: '#fe5858',
    fontWeight: 'bold',
  },
  toptext1: {
    fontSize: scale(25),
    color: 'black',
  },
  bottext1: {
    fontSize: scale(20),
    color: '#c0c0c0',
  },
  text1: {
    height: scale(70),
    width: scale(175),
    backgroundColor: '#f2f2f2',
    flexDirection: 'column',
    alignItems: 'center',
  },
  flag: {
    height: scale(30),
    width: scale(45),
  },
  casestext: {
    fontSize: scale(25),
    color: '#fe5858',
    textAlign: 'right',
    flex: 1,
    fontWeight: 'bold',
  },
  dataVN: {
    fontSize: scale(25),
  },
  viewVN: {
    marginLeft: scale(25),
    flexDirection: 'row',
    height: scale(48),
    justifyContent: 'center',
  },
  datacaseVN: {
    fontSize: scale(25),
    color: '#fe5858',
    textAlign: 'right',
    flex: 1,
    marginRight: scale(25),
    fontWeight: 'bold',
  },
  countryname: {
    fontSize: scale(25),
    marginLeft: scale(10),
  },
  searchbar: {
    backgroundColor: 'white',
    height: scale(50),
    width: scale(330),
    borderRadius: scale(20),
    flexDirection: 'row',
    alignItems: 'center',
  },
  icon: {
    marginLeft: scale(10),
  },
  searchtext: {
    fontSize: scale(15),
  },
  background: {
    flex: 1,
  },
  detailtop: {
    height: scale(270),
    alignItems: 'center',
    marginTop: scale(10),
  },
  detailmid: {
    height: scale(100),
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  bigdetaildata: {
    height: scale(100),
    width: scale(175),
    flexDirection: 'column',
    alignItems: 'center',
    marginTop: scale(65),
  },
  detaildata: {
    height: scale(100),
    width: scale(150),
    flexDirection: 'column',
    alignItems: 'center',
    backgroundColor: '#98fb8e',
    borderTopLeftRadius: scale(15),
    borderTopRightRadius: scale(15),
    justifyContent: 'center',
  },
  tinydetaildata: {
    height: scale(40),
    width: scale(150),
    flexDirection: 'column',
    alignItems: 'center',
    backgroundColor: '#70c567',
    borderBottomLeftRadius: scale(15),
    borderBottomRightRadius: scale(15),
    justifyContent: 'center',
  },
  detaildata1: {
    height: scale(100),
    width: scale(150),
    flexDirection: 'column',
    alignItems: 'center',
    backgroundColor: '#a3a3a3',
    borderTopLeftRadius: scale(15),
    borderTopRightRadius: scale(15),
    justifyContent: 'center',
  },
  tinydetaildata1: {
    height: scale(40),
    width: scale(150),
    flexDirection: 'column',
    alignItems: 'center',
    backgroundColor: '#5e5e5d',
    borderBottomLeftRadius: scale(15),
    borderBottomRightRadius: scale(15),
    justifyContent: 'center',
  },
  detaildata2: {
    marginTop: scale(70),
    height: scale(100),
    width: scale(150),
    flexDirection: 'column',
    alignItems: 'center',
    backgroundColor: '#f0a8a8',
    borderTopLeftRadius: scale(15),
    borderTopRightRadius: scale(15),
    justifyContent: 'center',
  },
  tinydetaildata2: {
    height: scale(40),
    width: scale(150),
    flexDirection: 'column',
    alignItems: 'center',
    backgroundColor: '#cc3737',
    borderBottomLeftRadius: scale(15),
    borderBottomRightRadius: scale(15),
    justifyContent: 'center',
  },
  detaildata3: {
    marginTop: scale(70),
    height: scale(100),
    width: scale(150),
    flexDirection: 'column',
    alignItems: 'center',
    backgroundColor: '#7facf8',
    borderTopLeftRadius: scale(15),
    borderTopRightRadius: scale(15),
    justifyContent: 'center',
  },
  tinydetaildata3: {
    height: scale(40),
    width: scale(150),
    flexDirection: 'column',
    alignItems: 'center',
    backgroundColor: '#5c8ad8',
    borderBottomLeftRadius: scale(15),
    borderBottomRightRadius: scale(15),
    justifyContent: 'center',
  },
  datatext: {
    fontSize: scale(28),
    color: 'white',
    fontWeight: 'bold',
  },
  bigflag: {
    height: scale(140),
    width: scale(230),
    borderRadius: scale(5),
  },
  topdetail: {
    fontSize: scale(50),
    color: '#fe5858',
    fontWeight: 'bold',
  },
  datatitletext: {
    fontSize: scale(18),
    color: 'white',
  },
  databottext: {
    fontSize: scale(14),
    fontWeight: 'bold',
    color: '#5c5e5c',
  },
  loader: {
    marginTop: scale(10),
    alignItems: 'center'
  },
});
export default styles;
